### ISSUE TITLE
ask for the pre-trained model

### ISSUE THREAD

**Issue by F1ZZZO** [stypoumic/BECLR#3]
This works really good, BTW, can I get the miniimagenet_r18 and miniimagenet_r50 epcho_400_pth, TY.

**Comment by stypoumic** [comment]
Checkpoints can be found on [Google Drive](https://drive.google.com/drive/folders/1E0guwYy3i97x1HEti-ld36JFvPWdwuhA?usp=sharing).

**Comment by F1ZZZO** [comment]
Thanks for reply！
